version: '3.4'

services:
  mitiendams.api.libro:
    image: ${DOCKER_REGISTRY-}mitiendamsapilibro
    build:
      context: .
      dockerfile: MiTiendaMS.Api.Libro/Dockerfile
  mitiendams.api.autor:
    image: ${DOCKER_REGISTRY-}mitiendamsapiautor
    build:
      context: .
      dockerfile: MiTiendaMS.Api.Autor/Dockerfile
  mitiendams.api.gateway:
    image: ${DOCKER_REGISTRY-}mitiendamsapigateway
    build:
      context: .
      dockerfile: MiTiendaMS.Api.Gateway/Dockerfile

networks:
  default:
    external:
      name: mitiendams_network

